[package]
name = "db_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
nosql_db = { path = "../nosql_db" }

[dev-dependencies]
criterion = "0.3"
redis = "0.21.0"
tokio = { version = "1.0", features = ["full"] }

[[bench]]
name = "database_benchmark"
harness = false

